# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_coding_demo',
                'doc_host': 'https://surenoobster.github.io',
                'git_url': 'https://github.com/surenoobster/nbdev_coding_demo',
                'lib_path': 'nbdev_coding_demo'},
  'syms': { 'nbdev_coding_demo.core': { 'nbdev_coding_demo.core.add': ('core.html#add', 'nbdev_coding_demo/core.py'),
                                        'nbdev_coding_demo.core.foo': ('core.html#foo', 'nbdev_coding_demo/core.py')}}}
